### PR TITLE
update hiop interface due to the latest changes in hiop

### LINKED ISSUE #28: Fail to compile ExaGO via Spack
I tried to use my own formula to install ExaGo via Spack, in order to debug 2 open issues.

In my Mac, I use the following formula:
```
exago@develop%gcc@13.2.0~cuda+hiop~ipo+ipopt+logging+mpi~python~raja~rocm build_system=cmake build_type=Release generator=make arch=darwin-bigsur-skylake
```
All my dependencies can be installed correctly, but I got the following error when I install ExaGO:

```
/var/folders/nl/p1j2_sbx6hvgn0plnyxkjks4001134/T/chiang7/spack-stage/spack-stage-exago-develop-4znpobq4x7emu4yqg2fu6yyznpw4l2dr/spack-src/src/scopflow/solver/hiop/scopflow_hiop.h:30:10: error: conflicting return type specified for 'virtual size_t SCOPFLOWHIOPInterface::get_num_rterms() const'

/var/folders/nl/p1j2_sbx6hvgn0plnyxkjks4001134/T/chiang7/spack-stage/spack-stage-exago-develop-4znpobq4x7emu4yqg2fu6yyznpw4l2dr/spack-src/src/scopflow/solver/hiop/scopflow_hiop.h:32:10: error: conflicting return type specified for 'virtual size_t SCOPFLOWHIOPInterface::get_num_vars() const'

/var/folders/nl/p1j2_sbx6hvgn0plnyxkjks4001134/T/chiang7/spack-stage/spack-stage-exago-develop-4znpobq4x7emu4yqg2fu6yyznpw4l2dr/spack-src/src/scopflow/solver/hiop/scopflow_hiop.cpp:542:59: error: invalid new-expression of abstract class type 'SCOPFLOWHIOPInterface'
```

Note that I got the same error when I tried to install ExaGO with python and raja on LLNL platforms.

Have you ever seen these errors and do we have any quick solution?

@abhyshr @pelesh @cameronrutherford

### PR DESCRIPTION
**Pull request by nychiang**
update hiop interface due to the latest developments in hiop

CLOSE #28

### CODE REVIEW

**Comment by cameronrutherford** [comment]
I think we want #20 merged before this, and perhaps need to resolve #10 for Ascent in CI to make this trivial to re-build and test. Thanks for the fix @nychiang, and hopefully we can merge this soon once we wrap up P6 and reporting activities.

We are also gearing up for a release soon, but might delay in favor of debugging this and getting compatibility back with hiop@1.0.0 working...

**Comment by cameronrutherford** [comment]
@nychiang I might just have this re-target #20, and have that branch do the re-builds automatically :)

**Comment by cameronrutherford** [comment]
Included changes in #20. Will close issue in that PR. Thanks @nychiang 

p.s. hopefully whenever hiop@develop has changes, we can use some pipelines to make a PR into exago and verify it doesn't break our build/tests. I will open a PR with this next quarter if I can find time

**Comment by cameronrutherford** [comment]
Since this change isn't necessary to build with 1.0.0, we are going to pin that version for our release, and then re-visit `hiop@develop` capability.

**Comment by jaelynlitz** [comment]
Is this ready to merge?

**Comment by cameronrutherford** [comment]
> Is this ready to merge?

Pipelines are failing, so no

**Comment by jaelynlitz** [comment]
closing as this was wrapped into #84
